# - Try to find Iconv 
# Once done this will define 
# 
#  ICONV_FOUND - system has Iconv 
#  ICONV_INCLUDE_DIR - the Iconv include directory 
#  ICONV_LIBRARY - Link these to use Iconv 
# 

SET(ICONV_DIR_SEARCH $ENV{ICONV_ROOT})

# do not use any standard paths without re-rooting
FIND_PATH(ICONV_INCLUDE_DIR NAMES iconv.h
  PATHS ${ICONV_DIR_SEARCH}/include
  NO_DEFAULT_PATH NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_FIND_ROOT_PATH
)
# if not found, use re-rooted standard paths
FIND_PATH(ICONV_INCLUDE_DIR NAMES iconv.h
  ONLY_CMAKE_FIND_ROOT_PATH
)

# do not use any standard paths without re-rooting
FIND_LIBRARY(ICONV_LIBRARY NAMES iconv c
  PATHS ${ICONV_DIR_SEARCH}/lib
  NO_DEFAULT_PATH NO_CMAKE_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
  NO_CMAKE_FIND_ROOT_PATH
)
# if not found, use re-rooted standard paths
FIND_LIBRARY(ICONV_LIBRARY NAMES iconv c
  PATHS 
  /usr/${LIB_DESTINATION}
  /usr/local/${LIB_DESTINATION}
  ONLY_CMAKE_FIND_ROOT_PATH
)
 
IF(ICONV_INCLUDE_DIR AND ICONV_LIBRARY) 
   SET(Iconv_FOUND TRUE) 
ENDIF(ICONV_INCLUDE_DIR AND ICONV_LIBRARY) 
 
#IF(Iconv_FOUND) 
#  IF(NOT Iconv_FIND_QUIETLY) 
#    MESSAGE(STATUS "Found Iconv: ${ICONV_LIBRARY}") 
#  ENDIF(NOT Iconv_FIND_QUIETLY) 
#ELSE(Iconv_FOUND) 
#  IF(Iconv_FIND_REQUIRED) 
#    MESSAGE(FATAL_ERROR "Could not find Iconv") 
#  ENDIF(Iconv_FIND_REQUIRED) 
#ENDIF(Iconv_FOUND) 

MARK_AS_ADVANCED(
  ICONV_INCLUDE_DIR
  ICONV_LIBRARY
)
