# specify the cross compiler
SET(CMAKE_C_COMPILER   i686-apple-darwin10-gcc CACHE STRING "CC")
SET(CMAKE_CXX_COMPILER i686-apple-darwin10-g++ CACHE STRING "CPP")
SET(CMAKE_RANLIB i686-apple-darwin10-ranlib CACHE STRING "RANLIB" FORCE)
SET(CMAKE_LIPO i686-apple-darwin10-lipo CACHE STRING "LIPO" FORCE)

SET(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_LIPO> -create <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_CXX_ARCHIVE_APPEND "<CMAKE_LIPO> -replace  <TARGET> <LINK_FLAGS> <OBJECTS>")

# set OSX-Version
SET(CMAKE_OSX_DEPLOYMENT_TARGET "10.5" CACHE STRING "OSX-Target")

# set SDK
SET(CMAKE_PREFIX_PATH "/srv/buildfarm/SDKs/MacOSX10.6.sdk")

# set root path
SET(CMAKE_FIND_ROOT_PATH "${CMAKE_PREFIX_PATH}")

IF ( NOT "${COMPILEARCH}" STREQUAL "" )
	SET(APPLE_CFLAGS "" CACHE STRING "Apple Flags")
	SET(APPLE_LDFLAGS "" CACHE STRING "Apple Link Flags")
	
	IF ( "${CMAKE_OSX_ARCHITECTURES}" MATCHES "x86_64" )
		SET(APPLE_CFLAGS "${APPLE_CFLAGS} -arch x86_64")
		SET(APPLE_LDFLAGS "${APPLE_LDFLAGS} -arch x86_64")
	ENDIF ( "${CMAKE_OSX_ARCHITECTURES}" MATCHES "x86_64" )
	
	IF ( "${CMAKE_OSX_ARCHITECTURES}" MATCHES "i386" )
		SET(APPLE_CFLAGS "${APPLE_CFLAGS} -arch i386")
		SET(APPLE_LDFLAGS "${APPLE_LDFLAGS} -arch i386")
	ENDIF ( "${CMAKE_OSX_ARCHITECTURES}" MATCHES "i386" )

	IF ( "${CMAKE_OSX_ARCHITECTURES}" MATCHES "ppc" )
		SET(APPLE_CFLAGS "${APPLE_CFLAGS} -arch ppc")
		SET(APPLE_LDFLAGS "${APPLE_LDFLAGS} -arch ppc")
	ENDIF ( "${CMAKE_OSX_ARCHITECTURES}" MATCHES "ppc" )

	# i386 only?
	IF ( NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "x86_64" AND NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "ppc" )
		SET(APPLE_FLAGS "${APPLE_FLAGS} -mtune=prescott -mmmx -mfpmath=sse -malign-double")
	ENDIF ( NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "x86_64" AND NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "ppc" )

	# ppc only?
	IF ( NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "x86_64" AND NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "i386" )
		SET(APPLE_FLAGS "${APPLE_FLAGS} -faltivec")
	ENDIF ( NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "x86_64" AND NOT "${CMAKE_OSX_ARCHITECTURES}" MATCHES "i386" )

	# set compiler flags
	SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${APPLE_CFLAGS} -ffast-math -msse -fomit-frame-pointer"  CACHE STRING "CFLAGS" FORCE)
	SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${APPLE_CFLAGS} -ffast-math -msse -fomit-frame-pointer"  CACHE STRING "CXXFLAGS" FORCE)
	
	# set linker flags
	SET(CMAKE_C_LINK_FLAGS 	"${CMAKE_C_LINK_FLAGS} ${APPLE_LDFLAGS} -framework OpenGL -L${CMAKE_SOURCE_DIR}/macos -lSDLmain" CACHE STRING "LDFLAGS (C)")
	SET(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} ${APPLE_LDFLAGS} -framework OpenGL -L${CMAKE_SOURCE_DIR}/macos -lSDLmain" CACHE STRING "LDFLAGS (C++)")
ENDIF ( NOT "${COMPILEARCH}" STREQUAL "" )

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
